2019.03.15 21:12:16 LOG5[ui]: stunnel 5.44 on x86_64-pc-linux-gnu platform
2019.03.15 21:12:16 LOG5[ui]: Compiled/running with OpenSSL 1.1.0g  2 Nov 2017
2019.03.15 21:12:16 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
2019.03.15 21:12:16 LOG5[ui]: Reading configuration from file /home/sohailaw98/Desktop/a2_ssd/A2_SSD/MSbin/stunnel/dev_https
2019.03.15 21:12:16 LOG5[ui]: UTF-8 byte order mark not detected
2019.03.15 21:12:16 LOG5[ui]: FIPS mode disabled
2019.03.15 21:12:16 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2019.03.15 21:12:16 LOG5[ui]: Configuration successful
2019.03.15 21:13:16 LOG5[cron]: Updating DH parameters
2019.03.15 21:13:21 LOG5[0]: Service [https] accepted connection from 127.0.0.1:36964
2019.03.15 21:13:21 LOG5[1]: Service [https] accepted connection from 127.0.0.1:36966
2019.03.15 21:13:21 LOG5[2]: Service [https] accepted connection from 127.0.0.1:36968
2019.03.15 21:13:21 LOG3[0]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:13:21 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:13:21 LOG5[3]: Service [https] accepted connection from 127.0.0.1:36970
2019.03.15 21:13:21 LOG3[3]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:13:21 LOG5[3]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:13:21 LOG3[2]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:13:21 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:13:21 LOG3[1]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:13:21 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:13:21 LOG5[4]: Service [https] accepted connection from 127.0.0.1:36974
2019.03.15 21:13:21 LOG3[4]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:13:21 LOG5[4]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:13:21 LOG5[5]: Service [https] accepted connection from 127.0.0.1:36976
2019.03.15 21:13:21 LOG3[5]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:13:21 LOG5[5]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:13:21 LOG5[6]: Service [https] accepted connection from 127.0.0.1:36978
2019.03.15 21:13:21 LOG3[6]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:13:21 LOG5[6]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:13:21 LOG5[7]: Service [https] accepted connection from 127.0.0.1:36980
2019.03.15 21:13:21 LOG3[7]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:13:21 LOG5[7]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:13:21 LOG5[8]: Service [https] accepted connection from 127.0.0.1:36982
2019.03.15 21:13:21 LOG3[8]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:13:21 LOG5[8]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:13:21 LOG5[9]: Service [https] accepted connection from 127.0.0.1:36984
2019.03.15 21:13:21 LOG3[9]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:13:21 LOG5[9]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:13:52 LOG5[cron]: DH parameters updated
2019.03.15 21:17:03 LOG5[10]: Service [https] accepted connection from 127.0.0.1:36998
2019.03.15 21:17:03 LOG3[10]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:03 LOG5[10]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:03 LOG5[11]: Service [https] accepted connection from 127.0.0.1:37000
2019.03.15 21:17:03 LOG3[11]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:03 LOG5[11]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:03 LOG5[12]: Service [https] accepted connection from 127.0.0.1:37002
2019.03.15 21:17:03 LOG3[12]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:03 LOG5[12]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:03 LOG5[13]: Service [https] accepted connection from 127.0.0.1:37004
2019.03.15 21:17:03 LOG3[13]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:03 LOG5[13]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:03 LOG5[14]: Service [https] accepted connection from 127.0.0.1:37006
2019.03.15 21:17:03 LOG3[14]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:03 LOG5[14]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:03 LOG5[15]: Service [https] accepted connection from 127.0.0.1:37008
2019.03.15 21:17:03 LOG3[15]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:03 LOG5[15]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:03 LOG5[16]: Service [https] accepted connection from 127.0.0.1:37010
2019.03.15 21:17:03 LOG3[16]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:03 LOG5[16]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:03 LOG5[17]: Service [https] accepted connection from 127.0.0.1:37012
2019.03.15 21:17:03 LOG3[17]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:03 LOG5[17]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:03 LOG5[18]: Service [https] accepted connection from 127.0.0.1:37014
2019.03.15 21:17:03 LOG3[18]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:03 LOG5[18]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:03 LOG5[19]: Service [https] accepted connection from 127.0.0.1:37016
2019.03.15 21:17:03 LOG3[19]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:03 LOG5[19]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[20]: Service [https] accepted connection from 127.0.0.1:37018
2019.03.15 21:17:05 LOG3[20]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[20]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[21]: Service [https] accepted connection from 127.0.0.1:37020
2019.03.15 21:17:05 LOG3[21]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[21]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[22]: Service [https] accepted connection from 127.0.0.1:37022
2019.03.15 21:17:05 LOG3[22]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[22]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[23]: Service [https] accepted connection from 127.0.0.1:37024
2019.03.15 21:17:05 LOG3[23]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[23]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[24]: Service [https] accepted connection from 127.0.0.1:37026
2019.03.15 21:17:05 LOG3[24]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[24]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[25]: Service [https] accepted connection from 127.0.0.1:37028
2019.03.15 21:17:05 LOG3[25]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[25]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[26]: Service [https] accepted connection from 127.0.0.1:37030
2019.03.15 21:17:05 LOG3[26]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[26]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[27]: Service [https] accepted connection from 127.0.0.1:37032
2019.03.15 21:17:05 LOG3[27]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[27]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[28]: Service [https] accepted connection from 127.0.0.1:37034
2019.03.15 21:17:05 LOG3[28]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[28]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[29]: Service [https] accepted connection from 127.0.0.1:37036
2019.03.15 21:17:05 LOG3[29]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[29]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[30]: Service [https] accepted connection from 127.0.0.1:37038
2019.03.15 21:17:05 LOG3[30]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[30]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[31]: Service [https] accepted connection from 127.0.0.1:37040
2019.03.15 21:17:05 LOG3[31]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[31]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[32]: Service [https] accepted connection from 127.0.0.1:37042
2019.03.15 21:17:05 LOG3[32]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[32]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[33]: Service [https] accepted connection from 127.0.0.1:37044
2019.03.15 21:17:05 LOG3[33]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[33]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[34]: Service [https] accepted connection from 127.0.0.1:37046
2019.03.15 21:17:05 LOG3[34]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[34]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[35]: Service [https] accepted connection from 127.0.0.1:37048
2019.03.15 21:17:05 LOG3[35]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[35]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[36]: Service [https] accepted connection from 127.0.0.1:37050
2019.03.15 21:17:05 LOG3[36]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[36]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[37]: Service [https] accepted connection from 127.0.0.1:37052
2019.03.15 21:17:05 LOG3[37]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[37]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[38]: Service [https] accepted connection from 127.0.0.1:37054
2019.03.15 21:17:05 LOG3[38]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[38]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:05 LOG5[39]: Service [https] accepted connection from 127.0.0.1:37056
2019.03.15 21:17:05 LOG3[39]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:05 LOG5[39]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[40]: Service [https] accepted connection from 127.0.0.1:37058
2019.03.15 21:17:06 LOG3[40]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[40]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[41]: Service [https] accepted connection from 127.0.0.1:37060
2019.03.15 21:17:06 LOG3[41]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[41]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[42]: Service [https] accepted connection from 127.0.0.1:37062
2019.03.15 21:17:06 LOG3[42]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[42]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[43]: Service [https] accepted connection from 127.0.0.1:37064
2019.03.15 21:17:06 LOG3[43]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[43]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[44]: Service [https] accepted connection from 127.0.0.1:37066
2019.03.15 21:17:06 LOG3[44]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[44]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[45]: Service [https] accepted connection from 127.0.0.1:37068
2019.03.15 21:17:06 LOG3[45]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[45]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[46]: Service [https] accepted connection from 127.0.0.1:37070
2019.03.15 21:17:06 LOG3[46]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[46]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[47]: Service [https] accepted connection from 127.0.0.1:37072
2019.03.15 21:17:06 LOG3[47]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[47]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[48]: Service [https] accepted connection from 127.0.0.1:37074
2019.03.15 21:17:06 LOG3[48]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[48]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[49]: Service [https] accepted connection from 127.0.0.1:37076
2019.03.15 21:17:06 LOG3[49]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[49]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[50]: Service [https] accepted connection from 127.0.0.1:37078
2019.03.15 21:17:06 LOG3[50]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[50]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[51]: Service [https] accepted connection from 127.0.0.1:37080
2019.03.15 21:17:06 LOG3[51]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[51]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[52]: Service [https] accepted connection from 127.0.0.1:37082
2019.03.15 21:17:06 LOG3[52]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[52]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[53]: Service [https] accepted connection from 127.0.0.1:37084
2019.03.15 21:17:06 LOG3[53]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[53]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[54]: Service [https] accepted connection from 127.0.0.1:37086
2019.03.15 21:17:06 LOG3[54]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[54]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[55]: Service [https] accepted connection from 127.0.0.1:37088
2019.03.15 21:17:06 LOG3[55]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[55]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[56]: Service [https] accepted connection from 127.0.0.1:37090
2019.03.15 21:17:06 LOG3[56]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[56]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[57]: Service [https] accepted connection from 127.0.0.1:37092
2019.03.15 21:17:06 LOG3[57]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[57]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[58]: Service [https] accepted connection from 127.0.0.1:37094
2019.03.15 21:17:06 LOG3[58]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[58]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[59]: Service [https] accepted connection from 127.0.0.1:37096
2019.03.15 21:17:06 LOG3[59]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[59]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[60]: Service [https] accepted connection from 127.0.0.1:37098
2019.03.15 21:17:06 LOG3[60]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[60]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[61]: Service [https] accepted connection from 127.0.0.1:37100
2019.03.15 21:17:06 LOG3[61]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[61]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[62]: Service [https] accepted connection from 127.0.0.1:37102
2019.03.15 21:17:06 LOG3[62]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[62]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[63]: Service [https] accepted connection from 127.0.0.1:37104
2019.03.15 21:17:06 LOG3[63]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[63]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[64]: Service [https] accepted connection from 127.0.0.1:37106
2019.03.15 21:17:06 LOG3[64]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[64]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[65]: Service [https] accepted connection from 127.0.0.1:37108
2019.03.15 21:17:06 LOG3[65]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[65]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[66]: Service [https] accepted connection from 127.0.0.1:37110
2019.03.15 21:17:06 LOG3[66]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[66]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[67]: Service [https] accepted connection from 127.0.0.1:37112
2019.03.15 21:17:06 LOG3[67]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[67]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[68]: Service [https] accepted connection from 127.0.0.1:37114
2019.03.15 21:17:06 LOG3[68]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[68]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:17:06 LOG5[69]: Service [https] accepted connection from 127.0.0.1:37116
2019.03.15 21:17:06 LOG3[69]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:17:06 LOG5[69]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:28 LOG5[70]: Service [https] accepted connection from 127.0.0.1:37136
2019.03.15 21:18:28 LOG3[70]: s_connect: connect ::1:8443: Connection refused (111)
2019.03.15 21:18:28 LOG5[70]: s_connect: connected 127.0.0.1:8443
2019.03.15 21:18:28 LOG5[70]: Service [https] connected remote server from 127.0.0.1:37140
2019.03.15 21:18:28 LOG5[71]: Service [https] accepted connection from 127.0.0.1:37140
2019.03.15 21:18:28 LOG3[70]: SSL_read: 14094412: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
2019.03.15 21:18:28 LOG5[70]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:28 LOG3[71]: SSL_accept: Peer suddenly disconnected
2019.03.15 21:18:28 LOG5[71]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:28 LOG5[72]: Service [https] accepted connection from 127.0.0.1:37142
2019.03.15 21:18:28 LOG3[72]: s_connect: connect ::1:8443: Connection refused (111)
2019.03.15 21:18:28 LOG5[72]: s_connect: connected 127.0.0.1:8443
2019.03.15 21:18:28 LOG5[72]: Service [https] connected remote server from 127.0.0.1:37146
2019.03.15 21:18:28 LOG3[72]: SSL_read: 14094412: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
2019.03.15 21:18:28 LOG5[73]: Service [https] accepted connection from 127.0.0.1:37146
2019.03.15 21:18:28 LOG5[72]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:28 LOG3[73]: SSL_accept: Peer suddenly disconnected
2019.03.15 21:18:28 LOG5[73]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[74]: Service [https] accepted connection from 127.0.0.1:37150
2019.03.15 21:18:44 LOG3[74]: s_connect: connect ::1:8443: Connection refused (111)
2019.03.15 21:18:44 LOG5[74]: s_connect: connected 127.0.0.1:8443
2019.03.15 21:18:44 LOG5[74]: Service [https] connected remote server from 127.0.0.1:37154
2019.03.15 21:18:44 LOG5[75]: Service [https] accepted connection from 127.0.0.1:37154
2019.03.15 21:18:44 LOG3[75]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:18:44 LOG5[75]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[74]: Connection closed: 0 byte(s) sent to TLS, 433 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[76]: Service [https] accepted connection from 127.0.0.1:37156
2019.03.15 21:18:44 LOG5[76]: s_connect: connected 127.0.0.1:8443
2019.03.15 21:18:44 LOG5[76]: Service [https] connected remote server from 127.0.0.1:37158
2019.03.15 21:18:44 LOG5[77]: Service [https] accepted connection from 127.0.0.1:37158
2019.03.15 21:18:44 LOG3[77]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:18:44 LOG5[77]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[76]: Connection closed: 0 byte(s) sent to TLS, 433 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[78]: Service [https] accepted connection from 127.0.0.1:37160
2019.03.15 21:18:44 LOG5[78]: s_connect: connected 127.0.0.1:8443
2019.03.15 21:18:44 LOG5[78]: Service [https] connected remote server from 127.0.0.1:37162
2019.03.15 21:18:44 LOG5[79]: Service [https] accepted connection from 127.0.0.1:37162
2019.03.15 21:18:44 LOG3[79]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:18:44 LOG5[79]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[78]: Connection closed: 0 byte(s) sent to TLS, 433 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[80]: Service [https] accepted connection from 127.0.0.1:37164
2019.03.15 21:18:44 LOG5[80]: s_connect: connected 127.0.0.1:8443
2019.03.15 21:18:44 LOG5[80]: Service [https] connected remote server from 127.0.0.1:37166
2019.03.15 21:18:44 LOG5[81]: Service [https] accepted connection from 127.0.0.1:37166
2019.03.15 21:18:44 LOG3[81]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:18:44 LOG5[81]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[80]: Connection closed: 0 byte(s) sent to TLS, 433 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[82]: Service [https] accepted connection from 127.0.0.1:37168
2019.03.15 21:18:44 LOG5[82]: s_connect: connected 127.0.0.1:8443
2019.03.15 21:18:44 LOG5[82]: Service [https] connected remote server from 127.0.0.1:37170
2019.03.15 21:18:44 LOG5[83]: Service [https] accepted connection from 127.0.0.1:37170
2019.03.15 21:18:44 LOG3[83]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:18:44 LOG5[83]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[82]: Connection closed: 0 byte(s) sent to TLS, 433 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[84]: Service [https] accepted connection from 127.0.0.1:37172
2019.03.15 21:18:44 LOG5[84]: s_connect: connected 127.0.0.1:8443
2019.03.15 21:18:44 LOG5[85]: Service [https] accepted connection from 127.0.0.1:37174
2019.03.15 21:18:44 LOG5[84]: Service [https] connected remote server from 127.0.0.1:37174
2019.03.15 21:18:44 LOG3[85]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:18:44 LOG5[85]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[84]: Connection closed: 0 byte(s) sent to TLS, 433 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[86]: Service [https] accepted connection from 127.0.0.1:37176
2019.03.15 21:18:44 LOG5[86]: s_connect: connected 127.0.0.1:8443
2019.03.15 21:18:44 LOG5[86]: Service [https] connected remote server from 127.0.0.1:37178
2019.03.15 21:18:44 LOG5[87]: Service [https] accepted connection from 127.0.0.1:37178
2019.03.15 21:18:44 LOG3[87]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:18:44 LOG5[87]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[86]: Connection closed: 0 byte(s) sent to TLS, 433 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[88]: Service [https] accepted connection from 127.0.0.1:37180
2019.03.15 21:18:44 LOG5[88]: s_connect: connected 127.0.0.1:8443
2019.03.15 21:18:44 LOG5[89]: Service [https] accepted connection from 127.0.0.1:37182
2019.03.15 21:18:44 LOG5[88]: Service [https] connected remote server from 127.0.0.1:37182
2019.03.15 21:18:44 LOG3[89]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:18:44 LOG5[89]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[88]: Connection closed: 0 byte(s) sent to TLS, 433 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[90]: Service [https] accepted connection from 127.0.0.1:37184
2019.03.15 21:18:44 LOG5[90]: s_connect: connected 127.0.0.1:8443
2019.03.15 21:18:44 LOG5[90]: Service [https] connected remote server from 127.0.0.1:37186
2019.03.15 21:18:44 LOG5[91]: Service [https] accepted connection from 127.0.0.1:37186
2019.03.15 21:18:44 LOG3[91]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:18:44 LOG5[91]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[90]: Connection closed: 0 byte(s) sent to TLS, 433 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[92]: Service [https] accepted connection from 127.0.0.1:37188
2019.03.15 21:18:44 LOG5[92]: s_connect: connected 127.0.0.1:8443
2019.03.15 21:18:44 LOG5[92]: Service [https] connected remote server from 127.0.0.1:37190
2019.03.15 21:18:44 LOG5[93]: Service [https] accepted connection from 127.0.0.1:37190
2019.03.15 21:18:44 LOG3[93]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:18:44 LOG5[93]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:18:44 LOG5[92]: Connection closed: 0 byte(s) sent to TLS, 433 byte(s) sent to socket
2019.03.15 21:21:08 LOG5[ui]: stunnel 5.44 on x86_64-pc-linux-gnu platform
2019.03.15 21:21:08 LOG5[ui]: Compiled/running with OpenSSL 1.1.0g  2 Nov 2017
2019.03.15 21:21:08 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
2019.03.15 21:21:08 LOG5[ui]: Reading configuration from file /home/sohailaw98/Desktop/a2_ssd/A2_SSD/MSbin/stunnel/dev_https
2019.03.15 21:21:08 LOG5[ui]: UTF-8 byte order mark not detected
2019.03.15 21:21:08 LOG5[ui]: FIPS mode disabled
2019.03.15 21:21:08 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2019.03.15 21:21:08 LOG5[ui]: Configuration successful
2019.03.15 21:21:24 LOG5[0]: Service [https] accepted connection from 127.0.0.1:37264
2019.03.15 21:21:24 LOG3[0]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:21:24 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:21:24 LOG5[1]: Service [https] accepted connection from 127.0.0.1:37266
2019.03.15 21:21:24 LOG3[1]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:21:24 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:21:24 LOG5[2]: Service [https] accepted connection from 127.0.0.1:37268
2019.03.15 21:21:24 LOG3[2]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:21:24 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:21:24 LOG5[3]: Service [https] accepted connection from 127.0.0.1:37270
2019.03.15 21:21:24 LOG3[3]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:21:24 LOG5[3]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:21:24 LOG5[4]: Service [https] accepted connection from 127.0.0.1:37272
2019.03.15 21:21:24 LOG3[4]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:21:24 LOG5[4]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:21:24 LOG5[5]: Service [https] accepted connection from 127.0.0.1:37274
2019.03.15 21:21:24 LOG3[5]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:21:24 LOG5[5]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:21:24 LOG5[6]: Service [https] accepted connection from 127.0.0.1:37276
2019.03.15 21:21:24 LOG3[6]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:21:24 LOG5[6]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:21:24 LOG5[7]: Service [https] accepted connection from 127.0.0.1:37278
2019.03.15 21:21:24 LOG3[7]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:21:24 LOG5[7]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:21:24 LOG5[8]: Service [https] accepted connection from 127.0.0.1:37280
2019.03.15 21:21:24 LOG3[8]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:21:24 LOG5[8]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:21:24 LOG5[9]: Service [https] accepted connection from 127.0.0.1:37282
2019.03.15 21:21:24 LOG3[9]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:21:24 LOG5[9]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:21:45 LOG5[10]: Service [https] accepted connection from 127.0.0.1:37296
2019.03.15 21:21:45 LOG3[10]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:21:45 LOG5[10]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:21:45 LOG5[10]: Service [https] connected remote server from 127.0.0.1:39490
2019.03.15 21:21:45 LOG5[11]: Service [https] accepted connection from 127.0.0.1:37302
2019.03.15 21:21:45 LOG5[11]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:21:45 LOG5[11]: Service [https] connected remote server from 127.0.0.1:39494
2019.03.15 21:22:08 LOG5[cron]: Updating DH parameters
2019.03.15 21:22:51 LOG5[cron]: DH parameters updated
2019.03.15 21:23:45 LOG5[10]: Connection closed: 17338 byte(s) sent to TLS, 1282 byte(s) sent to socket
2019.03.15 21:23:50 LOG5[11]: Connection closed: 63583 byte(s) sent to TLS, 3112 byte(s) sent to socket
2019.03.15 21:24:06 LOG5[12]: Service [https] accepted connection from 127.0.0.1:37316
2019.03.15 21:24:06 LOG5[12]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:24:06 LOG5[12]: Service [https] connected remote server from 127.0.0.1:39508
2019.03.15 21:24:06 LOG5[13]: Service [https] accepted connection from 127.0.0.1:37326
2019.03.15 21:24:06 LOG3[12]: TLS socket closed (SSL_write) with 132 unsent byte(s)
2019.03.15 21:24:06 LOG5[12]: Connection reset: 4085 byte(s) sent to TLS, 835 byte(s) sent to socket
2019.03.15 21:24:06 LOG5[13]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:24:06 LOG5[13]: Service [https] connected remote server from 127.0.0.1:39518
2019.03.15 21:25:37 LOG5[13]: Connection closed: 1983 byte(s) sent to TLS, 394 byte(s) sent to socket
2019.03.15 21:27:49 LOG5[14]: Service [https] accepted connection from 127.0.0.1:37350
2019.03.15 21:27:49 LOG3[14]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:27:49 LOG5[14]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:27:49 LOG5[15]: Service [https] accepted connection from 127.0.0.1:37352
2019.03.15 21:27:49 LOG3[15]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:27:49 LOG5[15]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:27:49 LOG5[16]: Service [https] accepted connection from 127.0.0.1:37354
2019.03.15 21:27:49 LOG3[16]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:27:49 LOG5[16]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:27:49 LOG5[17]: Service [https] accepted connection from 127.0.0.1:37356
2019.03.15 21:27:49 LOG3[17]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:27:49 LOG5[17]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:27:49 LOG5[18]: Service [https] accepted connection from 127.0.0.1:37358
2019.03.15 21:27:49 LOG3[18]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:27:49 LOG5[18]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:27:49 LOG5[19]: Service [https] accepted connection from 127.0.0.1:37360
2019.03.15 21:27:49 LOG3[19]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:27:49 LOG5[19]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:27:49 LOG5[20]: Service [https] accepted connection from 127.0.0.1:37362
2019.03.15 21:27:49 LOG3[20]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:27:49 LOG5[20]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:27:49 LOG5[21]: Service [https] accepted connection from 127.0.0.1:37364
2019.03.15 21:27:49 LOG3[21]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:27:49 LOG5[21]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:27:49 LOG5[22]: Service [https] accepted connection from 127.0.0.1:37366
2019.03.15 21:27:49 LOG3[22]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:27:49 LOG5[22]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:27:49 LOG5[23]: Service [https] accepted connection from 127.0.0.1:37368
2019.03.15 21:27:49 LOG3[23]: SSL_accept: 1408F09C: error:1408F09C:SSL routines:ssl3_get_record:http request
2019.03.15 21:27:49 LOG5[23]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:27:59 LOG5[24]: Service [https] accepted connection from 127.0.0.1:37370
2019.03.15 21:27:59 LOG3[24]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:27:59 LOG3[24]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:27:59 LOG3[24]: No more addresses to connect
2019.03.15 21:27:59 LOG5[24]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:27:59 LOG5[25]: Service [https] accepted connection from 127.0.0.1:37376
2019.03.15 21:27:59 LOG3[25]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:27:59 LOG3[25]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:27:59 LOG3[25]: No more addresses to connect
2019.03.15 21:27:59 LOG5[25]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:09 LOG5[26]: Service [https] accepted connection from 127.0.0.1:37384
2019.03.15 21:28:09 LOG3[26]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[26]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[26]: No more addresses to connect
2019.03.15 21:28:09 LOG5[26]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:09 LOG5[27]: Service [https] accepted connection from 127.0.0.1:37390
2019.03.15 21:28:09 LOG5[27]: persistence: No cached address found
2019.03.15 21:28:09 LOG3[27]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[27]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[27]: No more addresses to connect
2019.03.15 21:28:09 LOG5[27]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:09 LOG5[28]: Service [https] accepted connection from 127.0.0.1:37396
2019.03.15 21:28:09 LOG5[28]: persistence: No cached address found
2019.03.15 21:28:09 LOG3[28]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[28]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[28]: No more addresses to connect
2019.03.15 21:28:09 LOG5[28]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:09 LOG5[29]: Service [https] accepted connection from 127.0.0.1:37402
2019.03.15 21:28:09 LOG5[29]: persistence: No cached address found
2019.03.15 21:28:09 LOG3[29]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[29]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[29]: No more addresses to connect
2019.03.15 21:28:09 LOG5[29]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:09 LOG5[30]: Service [https] accepted connection from 127.0.0.1:37408
2019.03.15 21:28:09 LOG5[30]: persistence: No cached address found
2019.03.15 21:28:09 LOG3[30]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[30]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[30]: No more addresses to connect
2019.03.15 21:28:09 LOG5[30]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:09 LOG5[31]: Service [https] accepted connection from 127.0.0.1:37414
2019.03.15 21:28:09 LOG5[31]: persistence: No cached address found
2019.03.15 21:28:09 LOG3[31]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[31]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[31]: No more addresses to connect
2019.03.15 21:28:09 LOG5[31]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:09 LOG5[32]: Service [https] accepted connection from 127.0.0.1:37420
2019.03.15 21:28:09 LOG5[32]: persistence: No cached address found
2019.03.15 21:28:09 LOG3[32]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[32]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[32]: No more addresses to connect
2019.03.15 21:28:09 LOG5[32]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:09 LOG5[33]: Service [https] accepted connection from 127.0.0.1:37426
2019.03.15 21:28:09 LOG5[33]: persistence: No cached address found
2019.03.15 21:28:09 LOG3[33]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[33]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[33]: No more addresses to connect
2019.03.15 21:28:09 LOG5[33]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:09 LOG5[34]: Service [https] accepted connection from 127.0.0.1:37432
2019.03.15 21:28:09 LOG5[34]: persistence: No cached address found
2019.03.15 21:28:09 LOG3[34]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[34]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[34]: No more addresses to connect
2019.03.15 21:28:09 LOG5[34]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:09 LOG5[35]: Service [https] accepted connection from 127.0.0.1:37438
2019.03.15 21:28:09 LOG5[35]: persistence: No cached address found
2019.03.15 21:28:09 LOG3[35]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[35]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[35]: No more addresses to connect
2019.03.15 21:28:09 LOG5[35]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:09 LOG5[36]: Service [https] accepted connection from 127.0.0.1:37444
2019.03.15 21:28:09 LOG5[36]: persistence: No cached address found
2019.03.15 21:28:09 LOG3[36]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[36]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:09 LOG3[36]: No more addresses to connect
2019.03.15 21:28:09 LOG5[36]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:12 LOG5[37]: Service [https] accepted connection from 127.0.0.1:37450
2019.03.15 21:28:12 LOG5[37]: persistence: No cached address found
2019.03.15 21:28:12 LOG3[37]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[37]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[37]: No more addresses to connect
2019.03.15 21:28:12 LOG5[37]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:12 LOG5[38]: Service [https] accepted connection from 127.0.0.1:37456
2019.03.15 21:28:12 LOG5[38]: persistence: No cached address found
2019.03.15 21:28:12 LOG3[38]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[38]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[38]: No more addresses to connect
2019.03.15 21:28:12 LOG5[38]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:12 LOG5[39]: Service [https] accepted connection from 127.0.0.1:37462
2019.03.15 21:28:12 LOG5[39]: persistence: No cached address found
2019.03.15 21:28:12 LOG3[39]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[39]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[39]: No more addresses to connect
2019.03.15 21:28:12 LOG5[39]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:12 LOG5[40]: Service [https] accepted connection from 127.0.0.1:37468
2019.03.15 21:28:12 LOG5[40]: persistence: No cached address found
2019.03.15 21:28:12 LOG3[40]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[40]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[40]: No more addresses to connect
2019.03.15 21:28:12 LOG5[40]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:12 LOG5[41]: Service [https] accepted connection from 127.0.0.1:37474
2019.03.15 21:28:12 LOG5[41]: persistence: No cached address found
2019.03.15 21:28:12 LOG3[41]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[41]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[41]: No more addresses to connect
2019.03.15 21:28:12 LOG5[41]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:12 LOG5[42]: Service [https] accepted connection from 127.0.0.1:37480
2019.03.15 21:28:12 LOG5[42]: persistence: No cached address found
2019.03.15 21:28:12 LOG3[42]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[42]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[42]: No more addresses to connect
2019.03.15 21:28:12 LOG5[42]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:12 LOG5[43]: Service [https] accepted connection from 127.0.0.1:37486
2019.03.15 21:28:12 LOG5[43]: persistence: No cached address found
2019.03.15 21:28:12 LOG3[43]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[43]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[43]: No more addresses to connect
2019.03.15 21:28:12 LOG5[43]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:12 LOG5[44]: Service [https] accepted connection from 127.0.0.1:37492
2019.03.15 21:28:12 LOG5[44]: persistence: No cached address found
2019.03.15 21:28:12 LOG3[44]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[44]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[44]: No more addresses to connect
2019.03.15 21:28:12 LOG5[44]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:12 LOG5[45]: Service [https] accepted connection from 127.0.0.1:37498
2019.03.15 21:28:12 LOG5[45]: persistence: No cached address found
2019.03.15 21:28:12 LOG3[45]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[45]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[45]: No more addresses to connect
2019.03.15 21:28:12 LOG5[45]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:12 LOG5[46]: Service [https] accepted connection from 127.0.0.1:37504
2019.03.15 21:28:12 LOG5[46]: persistence: No cached address found
2019.03.15 21:28:12 LOG3[46]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[46]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[46]: No more addresses to connect
2019.03.15 21:28:12 LOG5[46]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:12 LOG5[47]: Service [https] accepted connection from 127.0.0.1:37510
2019.03.15 21:28:12 LOG5[47]: persistence: No cached address found
2019.03.15 21:28:12 LOG3[47]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[47]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:12 LOG3[47]: No more addresses to connect
2019.03.15 21:28:12 LOG5[47]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:15 LOG5[48]: Service [https] accepted connection from 127.0.0.1:37516
2019.03.15 21:28:15 LOG5[48]: persistence: No cached address found
2019.03.15 21:28:15 LOG3[48]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[48]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[48]: No more addresses to connect
2019.03.15 21:28:15 LOG5[48]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:15 LOG5[49]: Service [https] accepted connection from 127.0.0.1:37522
2019.03.15 21:28:15 LOG5[49]: persistence: No cached address found
2019.03.15 21:28:15 LOG3[49]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[49]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[49]: No more addresses to connect
2019.03.15 21:28:15 LOG5[49]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:15 LOG5[50]: Service [https] accepted connection from 127.0.0.1:37528
2019.03.15 21:28:15 LOG5[50]: persistence: No cached address found
2019.03.15 21:28:15 LOG3[50]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[50]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[50]: No more addresses to connect
2019.03.15 21:28:15 LOG5[50]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:15 LOG5[51]: Service [https] accepted connection from 127.0.0.1:37534
2019.03.15 21:28:15 LOG5[51]: persistence: No cached address found
2019.03.15 21:28:15 LOG3[51]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[51]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[51]: No more addresses to connect
2019.03.15 21:28:15 LOG5[51]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:15 LOG5[52]: Service [https] accepted connection from 127.0.0.1:37540
2019.03.15 21:28:15 LOG5[52]: persistence: No cached address found
2019.03.15 21:28:15 LOG3[52]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[52]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[52]: No more addresses to connect
2019.03.15 21:28:15 LOG5[52]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:15 LOG5[53]: Service [https] accepted connection from 127.0.0.1:37546
2019.03.15 21:28:15 LOG5[53]: persistence: No cached address found
2019.03.15 21:28:15 LOG3[53]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[53]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[53]: No more addresses to connect
2019.03.15 21:28:15 LOG5[53]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:15 LOG5[54]: Service [https] accepted connection from 127.0.0.1:37552
2019.03.15 21:28:15 LOG5[54]: persistence: No cached address found
2019.03.15 21:28:15 LOG3[54]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[54]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:15 LOG3[54]: No more addresses to connect
2019.03.15 21:28:15 LOG5[54]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:16 LOG5[55]: Service [https] accepted connection from 127.0.0.1:37558
2019.03.15 21:28:16 LOG5[55]: persistence: No cached address found
2019.03.15 21:28:16 LOG3[55]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:16 LOG3[55]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:16 LOG3[55]: No more addresses to connect
2019.03.15 21:28:16 LOG5[55]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:16 LOG5[56]: Service [https] accepted connection from 127.0.0.1:37564
2019.03.15 21:28:16 LOG5[56]: persistence: No cached address found
2019.03.15 21:28:16 LOG3[56]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:16 LOG3[56]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:16 LOG3[56]: No more addresses to connect
2019.03.15 21:28:16 LOG5[56]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:16 LOG5[57]: Service [https] accepted connection from 127.0.0.1:37570
2019.03.15 21:28:16 LOG5[57]: persistence: No cached address found
2019.03.15 21:28:16 LOG3[57]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:16 LOG3[57]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:16 LOG3[57]: No more addresses to connect
2019.03.15 21:28:16 LOG5[57]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:16 LOG5[58]: Service [https] accepted connection from 127.0.0.1:37576
2019.03.15 21:28:16 LOG5[58]: persistence: No cached address found
2019.03.15 21:28:16 LOG3[58]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:16 LOG3[58]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:16 LOG3[58]: No more addresses to connect
2019.03.15 21:28:16 LOG5[58]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:16 LOG5[59]: Service [https] accepted connection from 127.0.0.1:37582
2019.03.15 21:28:16 LOG5[59]: persistence: No cached address found
2019.03.15 21:28:16 LOG3[59]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:16 LOG3[59]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:16 LOG3[59]: No more addresses to connect
2019.03.15 21:28:16 LOG5[59]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:47 LOG5[60]: Service [https] accepted connection from 127.0.0.1:37588
2019.03.15 21:28:47 LOG3[60]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[60]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[60]: No more addresses to connect
2019.03.15 21:28:47 LOG5[60]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:47 LOG5[61]: Service [https] accepted connection from 127.0.0.1:37594
2019.03.15 21:28:47 LOG5[61]: persistence: No cached address found
2019.03.15 21:28:47 LOG3[61]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[61]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[61]: No more addresses to connect
2019.03.15 21:28:47 LOG5[61]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:47 LOG5[62]: Service [https] accepted connection from 127.0.0.1:37600
2019.03.15 21:28:47 LOG5[62]: persistence: No cached address found
2019.03.15 21:28:47 LOG3[62]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[62]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[62]: No more addresses to connect
2019.03.15 21:28:47 LOG5[62]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:47 LOG5[63]: Service [https] accepted connection from 127.0.0.1:37606
2019.03.15 21:28:47 LOG5[63]: persistence: No cached address found
2019.03.15 21:28:47 LOG3[63]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[63]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[63]: No more addresses to connect
2019.03.15 21:28:47 LOG5[63]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:47 LOG5[64]: Service [https] accepted connection from 127.0.0.1:37612
2019.03.15 21:28:47 LOG5[64]: persistence: No cached address found
2019.03.15 21:28:47 LOG3[64]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[64]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[64]: No more addresses to connect
2019.03.15 21:28:47 LOG5[64]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:47 LOG5[65]: Service [https] accepted connection from 127.0.0.1:37618
2019.03.15 21:28:47 LOG5[65]: persistence: No cached address found
2019.03.15 21:28:47 LOG3[65]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[65]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[65]: No more addresses to connect
2019.03.15 21:28:47 LOG5[65]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:47 LOG5[66]: Service [https] accepted connection from 127.0.0.1:37624
2019.03.15 21:28:47 LOG5[66]: persistence: No cached address found
2019.03.15 21:28:47 LOG3[66]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[66]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[66]: No more addresses to connect
2019.03.15 21:28:47 LOG5[66]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:47 LOG5[67]: Service [https] accepted connection from 127.0.0.1:37630
2019.03.15 21:28:47 LOG5[67]: persistence: No cached address found
2019.03.15 21:28:47 LOG3[67]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[67]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[67]: No more addresses to connect
2019.03.15 21:28:47 LOG5[67]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:47 LOG5[68]: Service [https] accepted connection from 127.0.0.1:37636
2019.03.15 21:28:47 LOG5[68]: persistence: No cached address found
2019.03.15 21:28:47 LOG3[68]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[68]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[68]: No more addresses to connect
2019.03.15 21:28:47 LOG5[68]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:47 LOG5[69]: Service [https] accepted connection from 127.0.0.1:37642
2019.03.15 21:28:47 LOG5[69]: persistence: No cached address found
2019.03.15 21:28:47 LOG3[69]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[69]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[69]: No more addresses to connect
2019.03.15 21:28:47 LOG5[69]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:47 LOG5[70]: Service [https] accepted connection from 127.0.0.1:37648
2019.03.15 21:28:47 LOG5[70]: persistence: No cached address found
2019.03.15 21:28:47 LOG3[70]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[70]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[70]: No more addresses to connect
2019.03.15 21:28:47 LOG5[70]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:47 LOG5[71]: Service [https] accepted connection from 127.0.0.1:37654
2019.03.15 21:28:47 LOG5[71]: persistence: No cached address found
2019.03.15 21:28:47 LOG3[71]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[71]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:47 LOG3[71]: No more addresses to connect
2019.03.15 21:28:47 LOG5[71]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:51 LOG5[72]: Service [https] accepted connection from 127.0.0.1:37660
2019.03.15 21:28:51 LOG5[72]: persistence: No cached address found
2019.03.15 21:28:51 LOG3[72]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[72]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[72]: No more addresses to connect
2019.03.15 21:28:51 LOG5[72]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:51 LOG5[73]: Service [https] accepted connection from 127.0.0.1:37666
2019.03.15 21:28:51 LOG5[73]: persistence: No cached address found
2019.03.15 21:28:51 LOG3[73]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[73]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[73]: No more addresses to connect
2019.03.15 21:28:51 LOG5[73]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:51 LOG5[74]: Service [https] accepted connection from 127.0.0.1:37672
2019.03.15 21:28:51 LOG5[74]: persistence: No cached address found
2019.03.15 21:28:51 LOG3[74]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[74]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[74]: No more addresses to connect
2019.03.15 21:28:51 LOG5[74]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:51 LOG5[75]: Service [https] accepted connection from 127.0.0.1:37678
2019.03.15 21:28:51 LOG5[75]: persistence: No cached address found
2019.03.15 21:28:51 LOG3[75]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[75]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[75]: No more addresses to connect
2019.03.15 21:28:51 LOG5[75]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:51 LOG5[76]: Service [https] accepted connection from 127.0.0.1:37684
2019.03.15 21:28:51 LOG5[76]: persistence: No cached address found
2019.03.15 21:28:51 LOG3[76]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[76]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[76]: No more addresses to connect
2019.03.15 21:28:51 LOG5[76]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:51 LOG5[77]: Service [https] accepted connection from 127.0.0.1:37690
2019.03.15 21:28:51 LOG5[77]: persistence: No cached address found
2019.03.15 21:28:51 LOG3[77]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[77]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[77]: No more addresses to connect
2019.03.15 21:28:51 LOG5[77]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:51 LOG5[78]: Service [https] accepted connection from 127.0.0.1:37696
2019.03.15 21:28:51 LOG5[78]: persistence: No cached address found
2019.03.15 21:28:51 LOG3[78]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[78]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[78]: No more addresses to connect
2019.03.15 21:28:51 LOG5[78]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:51 LOG5[79]: Service [https] accepted connection from 127.0.0.1:37702
2019.03.15 21:28:51 LOG5[79]: persistence: No cached address found
2019.03.15 21:28:51 LOG3[79]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[79]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[79]: No more addresses to connect
2019.03.15 21:28:51 LOG5[79]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:51 LOG5[80]: Service [https] accepted connection from 127.0.0.1:37708
2019.03.15 21:28:51 LOG5[80]: persistence: No cached address found
2019.03.15 21:28:51 LOG3[80]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[80]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[80]: No more addresses to connect
2019.03.15 21:28:51 LOG5[80]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:51 LOG5[81]: Service [https] accepted connection from 127.0.0.1:37714
2019.03.15 21:28:51 LOG5[81]: persistence: No cached address found
2019.03.15 21:28:51 LOG3[81]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[81]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:51 LOG3[81]: No more addresses to connect
2019.03.15 21:28:51 LOG5[81]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:52 LOG5[82]: Service [https] accepted connection from 127.0.0.1:37720
2019.03.15 21:28:52 LOG5[82]: persistence: No cached address found
2019.03.15 21:28:52 LOG3[82]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[82]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[82]: No more addresses to connect
2019.03.15 21:28:52 LOG5[82]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:52 LOG5[83]: Service [https] accepted connection from 127.0.0.1:37726
2019.03.15 21:28:52 LOG5[83]: persistence: No cached address found
2019.03.15 21:28:52 LOG3[83]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[83]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[83]: No more addresses to connect
2019.03.15 21:28:52 LOG5[83]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:52 LOG5[84]: Service [https] accepted connection from 127.0.0.1:37732
2019.03.15 21:28:52 LOG5[84]: persistence: No cached address found
2019.03.15 21:28:52 LOG3[84]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[84]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[84]: No more addresses to connect
2019.03.15 21:28:52 LOG5[84]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:52 LOG5[85]: Service [https] accepted connection from 127.0.0.1:37738
2019.03.15 21:28:52 LOG5[85]: persistence: No cached address found
2019.03.15 21:28:52 LOG3[85]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[85]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[85]: No more addresses to connect
2019.03.15 21:28:52 LOG5[85]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:52 LOG5[86]: Service [https] accepted connection from 127.0.0.1:37744
2019.03.15 21:28:52 LOG5[86]: persistence: No cached address found
2019.03.15 21:28:52 LOG3[86]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[86]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[86]: No more addresses to connect
2019.03.15 21:28:52 LOG5[86]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:52 LOG5[87]: Service [https] accepted connection from 127.0.0.1:37750
2019.03.15 21:28:52 LOG5[87]: persistence: No cached address found
2019.03.15 21:28:52 LOG3[87]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[87]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[87]: No more addresses to connect
2019.03.15 21:28:52 LOG5[87]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:52 LOG5[88]: Service [https] accepted connection from 127.0.0.1:37756
2019.03.15 21:28:52 LOG5[88]: persistence: No cached address found
2019.03.15 21:28:52 LOG3[88]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[88]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[88]: No more addresses to connect
2019.03.15 21:28:52 LOG5[88]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:52 LOG5[89]: Service [https] accepted connection from 127.0.0.1:37762
2019.03.15 21:28:52 LOG5[89]: persistence: No cached address found
2019.03.15 21:28:52 LOG3[89]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[89]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[89]: No more addresses to connect
2019.03.15 21:28:52 LOG5[89]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:52 LOG5[90]: Service [https] accepted connection from 127.0.0.1:37768
2019.03.15 21:28:52 LOG5[90]: persistence: No cached address found
2019.03.15 21:28:52 LOG3[90]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[90]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[90]: No more addresses to connect
2019.03.15 21:28:52 LOG5[90]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:28:52 LOG5[91]: Service [https] accepted connection from 127.0.0.1:37774
2019.03.15 21:28:52 LOG5[91]: persistence: No cached address found
2019.03.15 21:28:52 LOG3[91]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[91]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:28:52 LOG3[91]: No more addresses to connect
2019.03.15 21:28:52 LOG5[91]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:06 LOG5[ui]: stunnel 5.44 on x86_64-pc-linux-gnu platform
2019.03.15 21:29:06 LOG5[ui]: Compiled/running with OpenSSL 1.1.0g  2 Nov 2017
2019.03.15 21:29:06 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
2019.03.15 21:29:06 LOG5[ui]: Reading configuration from file /home/sohailaw98/Desktop/a2_ssd/A2_SSD/MSbin/stunnel/dev_https
2019.03.15 21:29:06 LOG5[ui]: UTF-8 byte order mark not detected
2019.03.15 21:29:06 LOG5[ui]: FIPS mode disabled
2019.03.15 21:29:06 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2019.03.15 21:29:06 LOG5[ui]: Configuration successful
2019.03.15 21:29:13 LOG5[0]: Service [https] accepted connection from 127.0.0.1:37780
2019.03.15 21:29:13 LOG3[0]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[0]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[0]: No more addresses to connect
2019.03.15 21:29:13 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:13 LOG5[1]: Service [https] accepted connection from 127.0.0.1:37786
2019.03.15 21:29:13 LOG5[1]: persistence: No cached address found
2019.03.15 21:29:13 LOG3[1]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[1]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[1]: No more addresses to connect
2019.03.15 21:29:13 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:13 LOG5[2]: Service [https] accepted connection from 127.0.0.1:37792
2019.03.15 21:29:13 LOG5[2]: persistence: No cached address found
2019.03.15 21:29:13 LOG3[2]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[2]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[2]: No more addresses to connect
2019.03.15 21:29:13 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:13 LOG5[3]: Service [https] accepted connection from 127.0.0.1:37798
2019.03.15 21:29:13 LOG5[3]: persistence: No cached address found
2019.03.15 21:29:13 LOG3[3]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[3]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[3]: No more addresses to connect
2019.03.15 21:29:13 LOG5[3]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:13 LOG5[4]: Service [https] accepted connection from 127.0.0.1:37804
2019.03.15 21:29:13 LOG5[4]: persistence: No cached address found
2019.03.15 21:29:13 LOG3[4]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[4]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[4]: No more addresses to connect
2019.03.15 21:29:13 LOG5[4]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:13 LOG5[5]: Service [https] accepted connection from 127.0.0.1:37810
2019.03.15 21:29:13 LOG5[5]: persistence: No cached address found
2019.03.15 21:29:13 LOG3[5]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[5]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[5]: No more addresses to connect
2019.03.15 21:29:13 LOG5[5]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:13 LOG5[6]: Service [https] accepted connection from 127.0.0.1:37816
2019.03.15 21:29:13 LOG5[6]: persistence: No cached address found
2019.03.15 21:29:13 LOG3[6]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[6]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[6]: No more addresses to connect
2019.03.15 21:29:13 LOG5[6]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:13 LOG5[7]: Service [https] accepted connection from 127.0.0.1:37822
2019.03.15 21:29:13 LOG5[7]: persistence: No cached address found
2019.03.15 21:29:13 LOG3[7]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[7]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[7]: No more addresses to connect
2019.03.15 21:29:13 LOG5[7]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:13 LOG5[8]: Service [https] accepted connection from 127.0.0.1:37828
2019.03.15 21:29:13 LOG5[8]: persistence: No cached address found
2019.03.15 21:29:13 LOG3[8]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[8]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[8]: No more addresses to connect
2019.03.15 21:29:13 LOG5[8]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:13 LOG5[9]: Service [https] accepted connection from 127.0.0.1:37834
2019.03.15 21:29:13 LOG5[9]: persistence: No cached address found
2019.03.15 21:29:13 LOG3[9]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[9]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:13 LOG3[9]: No more addresses to connect
2019.03.15 21:29:13 LOG5[9]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:15 LOG5[10]: Service [https] accepted connection from 127.0.0.1:37840
2019.03.15 21:29:15 LOG5[10]: persistence: No cached address found
2019.03.15 21:29:15 LOG3[10]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[10]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[10]: No more addresses to connect
2019.03.15 21:29:15 LOG5[10]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:15 LOG5[11]: Service [https] accepted connection from 127.0.0.1:37846
2019.03.15 21:29:15 LOG5[11]: persistence: No cached address found
2019.03.15 21:29:15 LOG3[11]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[11]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[11]: No more addresses to connect
2019.03.15 21:29:15 LOG5[11]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:15 LOG5[12]: Service [https] accepted connection from 127.0.0.1:37852
2019.03.15 21:29:15 LOG5[12]: persistence: No cached address found
2019.03.15 21:29:15 LOG3[12]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[12]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[12]: No more addresses to connect
2019.03.15 21:29:15 LOG5[12]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:15 LOG5[13]: Service [https] accepted connection from 127.0.0.1:37858
2019.03.15 21:29:15 LOG5[13]: persistence: No cached address found
2019.03.15 21:29:15 LOG3[13]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[13]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[13]: No more addresses to connect
2019.03.15 21:29:15 LOG5[13]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:15 LOG5[14]: Service [https] accepted connection from 127.0.0.1:37864
2019.03.15 21:29:15 LOG5[14]: persistence: No cached address found
2019.03.15 21:29:15 LOG3[14]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[14]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[14]: No more addresses to connect
2019.03.15 21:29:15 LOG5[14]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:15 LOG5[15]: Service [https] accepted connection from 127.0.0.1:37870
2019.03.15 21:29:15 LOG5[15]: persistence: No cached address found
2019.03.15 21:29:15 LOG3[15]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[15]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[15]: No more addresses to connect
2019.03.15 21:29:15 LOG5[15]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:15 LOG5[16]: Service [https] accepted connection from 127.0.0.1:37876
2019.03.15 21:29:15 LOG5[16]: persistence: No cached address found
2019.03.15 21:29:15 LOG3[16]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[16]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[16]: No more addresses to connect
2019.03.15 21:29:15 LOG5[16]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:15 LOG5[17]: Service [https] accepted connection from 127.0.0.1:37882
2019.03.15 21:29:15 LOG5[17]: persistence: No cached address found
2019.03.15 21:29:15 LOG3[17]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[17]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[17]: No more addresses to connect
2019.03.15 21:29:15 LOG5[17]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:15 LOG5[18]: Service [https] accepted connection from 127.0.0.1:37888
2019.03.15 21:29:15 LOG5[18]: persistence: No cached address found
2019.03.15 21:29:15 LOG3[18]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[18]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[18]: No more addresses to connect
2019.03.15 21:29:15 LOG5[18]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:15 LOG5[19]: Service [https] accepted connection from 127.0.0.1:37894
2019.03.15 21:29:15 LOG5[19]: persistence: No cached address found
2019.03.15 21:29:15 LOG3[19]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[19]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:15 LOG3[19]: No more addresses to connect
2019.03.15 21:29:15 LOG5[19]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[20]: Service [https] accepted connection from 127.0.0.1:37900
2019.03.15 21:29:16 LOG5[20]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[20]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[20]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[20]: No more addresses to connect
2019.03.15 21:29:16 LOG5[20]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[21]: Service [https] accepted connection from 127.0.0.1:37906
2019.03.15 21:29:16 LOG5[21]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[21]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[21]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[21]: No more addresses to connect
2019.03.15 21:29:16 LOG5[21]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[22]: Service [https] accepted connection from 127.0.0.1:37912
2019.03.15 21:29:16 LOG5[22]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[22]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[22]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[22]: No more addresses to connect
2019.03.15 21:29:16 LOG5[22]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[23]: Service [https] accepted connection from 127.0.0.1:37918
2019.03.15 21:29:16 LOG5[23]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[23]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[23]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[23]: No more addresses to connect
2019.03.15 21:29:16 LOG5[23]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[24]: Service [https] accepted connection from 127.0.0.1:37924
2019.03.15 21:29:16 LOG5[24]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[24]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[24]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[24]: No more addresses to connect
2019.03.15 21:29:16 LOG5[24]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[25]: Service [https] accepted connection from 127.0.0.1:37930
2019.03.15 21:29:16 LOG5[25]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[25]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[25]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[25]: No more addresses to connect
2019.03.15 21:29:16 LOG5[25]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[26]: Service [https] accepted connection from 127.0.0.1:37936
2019.03.15 21:29:16 LOG5[26]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[26]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[26]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[26]: No more addresses to connect
2019.03.15 21:29:16 LOG5[26]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[27]: Service [https] accepted connection from 127.0.0.1:37942
2019.03.15 21:29:16 LOG5[27]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[27]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[27]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[27]: No more addresses to connect
2019.03.15 21:29:16 LOG5[27]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[28]: Service [https] accepted connection from 127.0.0.1:37948
2019.03.15 21:29:16 LOG5[28]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[28]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[28]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[28]: No more addresses to connect
2019.03.15 21:29:16 LOG5[28]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[29]: Service [https] accepted connection from 127.0.0.1:37954
2019.03.15 21:29:16 LOG5[29]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[29]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[29]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[29]: No more addresses to connect
2019.03.15 21:29:16 LOG5[29]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[30]: Service [https] accepted connection from 127.0.0.1:37960
2019.03.15 21:29:16 LOG5[30]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[30]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[30]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[30]: No more addresses to connect
2019.03.15 21:29:16 LOG5[30]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[31]: Service [https] accepted connection from 127.0.0.1:37966
2019.03.15 21:29:16 LOG5[31]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[31]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[31]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[31]: No more addresses to connect
2019.03.15 21:29:16 LOG5[31]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[32]: Service [https] accepted connection from 127.0.0.1:37972
2019.03.15 21:29:16 LOG5[32]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[32]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[32]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[32]: No more addresses to connect
2019.03.15 21:29:16 LOG5[32]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[33]: Service [https] accepted connection from 127.0.0.1:37978
2019.03.15 21:29:16 LOG5[33]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[33]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[33]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[33]: No more addresses to connect
2019.03.15 21:29:16 LOG5[33]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[34]: Service [https] accepted connection from 127.0.0.1:37984
2019.03.15 21:29:16 LOG5[34]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[34]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[34]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[34]: No more addresses to connect
2019.03.15 21:29:16 LOG5[34]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[35]: Service [https] accepted connection from 127.0.0.1:37990
2019.03.15 21:29:16 LOG5[35]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[35]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[35]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[35]: No more addresses to connect
2019.03.15 21:29:16 LOG5[35]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[36]: Service [https] accepted connection from 127.0.0.1:37996
2019.03.15 21:29:16 LOG5[36]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[36]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[36]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[36]: No more addresses to connect
2019.03.15 21:29:16 LOG5[36]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[37]: Service [https] accepted connection from 127.0.0.1:38002
2019.03.15 21:29:16 LOG5[37]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[37]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[37]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[37]: No more addresses to connect
2019.03.15 21:29:16 LOG5[37]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[38]: Service [https] accepted connection from 127.0.0.1:38008
2019.03.15 21:29:16 LOG5[38]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[38]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[38]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[38]: No more addresses to connect
2019.03.15 21:29:16 LOG5[38]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:29:16 LOG5[39]: Service [https] accepted connection from 127.0.0.1:38014
2019.03.15 21:29:16 LOG5[39]: persistence: No cached address found
2019.03.15 21:29:16 LOG3[39]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[39]: s_connect: connect 127.0.0.1:8001: Connection refused (111)
2019.03.15 21:29:16 LOG3[39]: No more addresses to connect
2019.03.15 21:29:16 LOG5[39]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:30:06 LOG5[cron]: Updating DH parameters
2019.03.15 21:30:20 LOG5[40]: Service [https] accepted connection from 127.0.0.1:38022
2019.03.15 21:30:20 LOG5[40]: persistence: No cached address found
2019.03.15 21:30:20 LOG5[40]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:30:20 LOG5[40]: Service [https] connected remote server from 127.0.0.1:40214
2019.03.15 21:30:20 LOG5[40]: Connection closed: 9475 byte(s) sent to TLS, 851 byte(s) sent to socket
2019.03.15 21:30:25 LOG5[41]: Service [https] accepted connection from 127.0.0.1:38026
2019.03.15 21:30:25 LOG5[41]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:30:25 LOG5[41]: Service [https] connected remote server from 127.0.0.1:40218
2019.03.15 21:31:24 LOG5[41]: Connection closed: 6014 byte(s) sent to TLS, 827 byte(s) sent to socket
2019.03.15 21:31:50 LOG5[cron]: DH parameters updated
2019.03.15 21:35:19 LOG5[ui]: stunnel 5.44 on x86_64-pc-linux-gnu platform
2019.03.15 21:35:19 LOG5[ui]: Compiled/running with OpenSSL 1.1.0g  2 Nov 2017
2019.03.15 21:35:19 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
2019.03.15 21:35:19 LOG5[ui]: Reading configuration from file /home/sohailaw98/Desktop/a2_ssd/A2_SSD/MSbin/stunnel/dev_https
2019.03.15 21:35:19 LOG5[ui]: UTF-8 byte order mark not detected
2019.03.15 21:35:19 LOG5[ui]: FIPS mode disabled
2019.03.15 21:35:19 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2019.03.15 21:35:19 LOG5[ui]: Configuration successful
2019.03.15 21:35:27 LOG5[ui]: stunnel 5.44 on x86_64-pc-linux-gnu platform
2019.03.15 21:35:27 LOG5[ui]: Compiled/running with OpenSSL 1.1.0g  2 Nov 2017
2019.03.15 21:35:27 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
2019.03.15 21:35:27 LOG5[ui]: Reading configuration from file /home/sohailaw98/Desktop/a2_ssd/A2_SSD/MSbin/stunnel/dev_https
2019.03.15 21:35:27 LOG5[ui]: UTF-8 byte order mark not detected
2019.03.15 21:35:27 LOG5[ui]: FIPS mode disabled
2019.03.15 21:35:27 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2019.03.15 21:35:27 LOG5[ui]: Configuration successful
2019.03.15 21:36:27 LOG5[cron]: Updating DH parameters
2019.03.15 21:37:01 LOG5[cron]: DH parameters updated
2019.03.15 21:37:18 LOG5[0]: Service [https] accepted connection from 127.0.0.1:38240
2019.03.15 21:37:18 LOG3[0]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:37:18 LOG5[0]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:37:18 LOG5[0]: Service [https] connected remote server from 127.0.0.1:40434
2019.03.15 21:37:18 LOG3[0]: TLS socket closed (SSL_write) with 169 unsent byte(s)
2019.03.15 21:37:18 LOG5[0]: Connection reset: 4048 byte(s) sent to TLS, 835 byte(s) sent to socket
2019.03.15 21:37:18 LOG5[1]: Service [https] accepted connection from 127.0.0.1:38254
2019.03.15 21:37:18 LOG5[1]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:37:18 LOG5[1]: Service [https] connected remote server from 127.0.0.1:40446
2019.03.15 21:37:19 LOG3[1]: TLS socket closed (SSL_write) with 75 unsent byte(s)
2019.03.15 21:37:19 LOG5[1]: Connection reset: 2007 byte(s) sent to TLS, 808 byte(s) sent to socket
2019.03.15 21:44:46 LOG5[2]: Service [https] accepted connection from 127.0.0.1:38278
2019.03.15 21:44:46 LOG3[2]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:44:46 LOG5[2]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:44:46 LOG5[2]: Service [https] connected remote server from 127.0.0.1:40472
2019.03.15 21:44:47 LOG5[3]: Service [https] accepted connection from 127.0.0.1:38284
2019.03.15 21:44:47 LOG5[3]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:44:47 LOG5[3]: Service [https] connected remote server from 127.0.0.1:40476
2019.03.15 21:44:47 LOG5[5]: Service [https] accepted connection from 127.0.0.1:38290
2019.03.15 21:44:47 LOG5[4]: Service [https] accepted connection from 127.0.0.1:38288
2019.03.15 21:44:47 LOG5[4]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:44:47 LOG5[4]: Service [https] connected remote server from 127.0.0.1:40482
2019.03.15 21:44:47 LOG5[5]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:44:47 LOG5[5]: Service [https] connected remote server from 127.0.0.1:40484
2019.03.15 21:50:09 LOG5[4]: Connection closed: 1216 byte(s) sent to TLS, 4088 byte(s) sent to socket
2019.03.15 21:52:49 LOG5[5]: Connection closed: 20618 byte(s) sent to TLS, 9665 byte(s) sent to socket
2019.03.15 21:52:49 LOG5[2]: Connection closed: 53837 byte(s) sent to TLS, 6923 byte(s) sent to socket
2019.03.15 21:52:49 LOG5[3]: Connection closed: 20944 byte(s) sent to TLS, 9679 byte(s) sent to socket
2019.03.15 21:54:53 LOG5[6]: Service [https] accepted connection from 127.0.0.1:38324
2019.03.15 21:54:53 LOG3[6]: s_connect: connect ::1:8001: Connection refused (111)
2019.03.15 21:54:53 LOG5[6]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:54:53 LOG5[6]: Service [https] connected remote server from 127.0.0.1:40518
2019.03.15 21:54:53 LOG5[7]: Service [https] accepted connection from 127.0.0.1:38334
2019.03.15 21:54:53 LOG5[7]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:54:53 LOG5[7]: Service [https] connected remote server from 127.0.0.1:40526
2019.03.15 21:54:53 LOG5[8]: Service [https] accepted connection from 127.0.0.1:38342
2019.03.15 21:54:53 LOG5[8]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:54:53 LOG5[8]: Service [https] connected remote server from 127.0.0.1:40534
2019.03.15 21:54:59 LOG5[8]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2019.03.15 21:56:20 LOG5[9]: Service [https] accepted connection from 127.0.0.1:38348
2019.03.15 21:56:20 LOG5[9]: s_connect: connected 127.0.0.1:8001
2019.03.15 21:56:20 LOG5[9]: Service [https] connected remote server from 127.0.0.1:40540
